improve y labels in plots
jaidevd/pyhht pull request #53
Opened 2018-08-21 13:08 UTC by ggrrll

here is my proposition to improve the plot:

- rotate and move a little -- to avoid overlap
- add a `_` to IMF names to make it more clear

#52

2018-08-21 13:13 UTC, jaidevd requested changes

2018-08-21 13:13 UTC, jaidevd commented on pyhht/visualization.py
> +    ax.set_ylabel('Signal',rotation=0)
Please expose the `rotation` parameter in the function definition so others can use it as they like. Keep the default as 0. Also please run `flake8` on the file and fix all related issues.

2018-08-21 13:13 UTC, jaidevd commented on pyhht/visualization.py
> +    ax.yaxis.set_label_coords(-0.1,0)
These parameters should also be exposed in the `plot_imfs` function, with these values as default.

2018-08-21 13:14 UTC, jaidevd commented
Please also make sure that Travis CI is passing.

2018-08-21 13:55 UTC, ggrrll commented
so, I add the flake8 test and the exposures  -- didn't have time for Travis CI (sorry, I am also quite new to these tests :) )

2018-08-21 13:59 UTC, jaidevd commented
Thanks a lot for this, @ggrrll 

It seems that the tests failing in travis are the plotting tests. Makes sense, since we have changed the plotting code here, but not the template images against which the generated plots are compared. Please take a look at this whenever you have time: https://matplotlib.org/1.5.3/devel/testing.html#writing-an-image-comparison-test

And let me know. Then we'll discuss how to fix these tests for the current changes.

Thanks again,

2018-08-23 10:15 UTC, ggrrll commented
sorry, my fault - 
[e76a08e](https://github.com/jaidevd/pyhht/pull/53/commits/e76a08e045824ffe779f2cc1108d17884ec57d26) is related to #54

2018-08-23 10:19 UTC, jaidevd commented
Please roll back the last commit, I've already fixed that reference in https://github.com/jaidevd/pyhht/commit/f4e6a044e57d34fc95f5bd2651ef2e232ce2d42b

2021-01-11 02:26 UTC, jaidevd commented
Closing for lack of activity.

2021-01-11 02:26 UTC, closed without merging